server:
  port: 9001
  servlet:
    context-path: /adapter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka/eureka
  instance:
    prefer-ip-address: true

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/acc_adapter?createDatabaseIfNotExist=true&characterEncoding=UTF8&rewriteBatchedStatements=true
    username: root
    password: root

  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      host: localhost
      port: 27017
      database: link
