server:
  port: 9003
  servlet:
    context-path: /loan

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka/eureka
  instance:
    prefer-ip-address: true
    #ip-address: 127.0.0.1

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/acc_loan?createDatabaseIfNotExist=true&characterEncoding=UTF8&rewriteBatchedStatements=true
    username: root
    password: root

  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

