server:
  port: 9002
  servlet:
    context-path: /batch

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8686/eureka/eureka
  instance:
    prefer-ip-address: true
    #ip-address: 127.0.0.1

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost/acc_batch?createDatabaseIfNotExist=true&characterEncoding=UTF8&rewriteBatchedStatements=true
    username: root
    password: root
  second:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.112.110.71:3306/test?createDatabaseIfNotExist=true&characterEncoding=UTF8&rewriteBatchedStatements=true
      username: root
      password: 123456
      type: com.zaxxer.hikari.HikariDataSource
  main:
    allow-bean-definition-overriding: true

  mail:
    host: smtp.qq.com
    port: 25
    username: 348691356
    password: rjivwjbadxuxcahf
    default-encoding: UTF-8

  #项目启动时不调用 Job
  batch:
    job:
      enabled: false
    initialize-schema: always
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update

sendMessage:
  send-from: 348691356@qq.com
  send-to: 348691356@qq.com,61906806@qq.com

swagger:
  basic:
    enable: true
    username: scy
    password: scy

mybatis:
  type-aliases-package: com.weshare.batch.entity
  mapper-locations: classpath:com/weshare/batch/mapper/*Mapper.xml
  #type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB








